import type CVData from './cvData.d';

export const cvData: CVData = {
    header: {
        name: {
            first: 'Luiz',
            middle: 'Gonzaga',
            last: 'dos Santos Filho',
            title: 'MBA',
        },
        location: {
            city: 'Vancouver',
            country: 'Canada',
        },
        contact: {
            phone: { raw: '', formatted: '' },
            url: { href: 'https://luiz.dev', display: 'www.luiz.dev' },
            email: 'lfilho@gmail.com',
            linkedin: {
                href: 'https://linkedin.com/in/luizgonzaga',
                display: '/luizgonzaga',
            },
            topmate: {
                href: 'https://topmate.io/luizgonzaga',
                display: '/luizgonzaga',
            },
            // twitter: {
            //     href: 'https://twitter.com/luizmarelo',
            //     display: '/luizmarelo',
            // },
            speakerdeck: {
                href: 'https://speakerdeck.com/lfilho',
                display: '/lfilho',
            },
            github: { href: 'https://github.com/lfilho', display: '/lfilho' },
        },
        introduction: [
            `A people first geek with {{CAREER_TIME}}+ years of building quality software and engaged teams in different countries and company sizes.`,
            `I focus on scaling organizations with efficient and low touch processes.`,
            `I'm continually adding to my thousands of hours of learning, and I love sharing what I know. Feel free to check some of my testimonials and recommendations on my LinkedIn and Topmate profiles.`,
        ],
    },
    experiences: {
        softwareEngineering: [
            {
                startDate: 'Feb 2021',
                endDate: 'present',
                company: 'Coursera',
                position: 'Senior Software Development Manager',
                keywords: ['edTech', 'education', 'aws'],
                description: [
                    `Managed several teams and charters in the Enterprise org:`,
                    [
                        `Responsible for key Enterprise metrics and projects, unlocking millions of dollars in revenue`,
                        `Responsible for key products like SkillSets, Employability and Admin experience`,
                        `Highest retention rate in the org`,
                        `Improved team's processes for better remote-first practices and more efficient collaboration with other teams and stakeholders`,
                    ],
                    `Organizational contributions:`,
                    [
                        `Created and owned several org-wide process, increasing key metrics, reducing touchpoints, increasing accountability and better equipping high leadership on critical decision making`,
                        `Created an org-wide policy, increasing inclusiveness and belonging`,
                        `Above average interview count`,
                        `Transitioned a Senior Engineer towards becoming an Engineering Manager`,
                        `Volunteered in the DE&I squad, helping come up and drive many of the org-wide goals taken in the area`,
                        `Improved our Postmortem process, automating and reducing high touch-points, enabling better accountability, metrics and easier knowledge sharing within the company`,
                        `Reduced context switching, improved documentation and efficiency for cross functional collaboration in Enterprise org's biggest cross-functional internal forum`,
                        `Proposed measurable improvements for other orgs (Recruiting and IT), increasing the hiring pipeline throughput and diversity`,
                    ],
                ],
            },
            {
                startDate: 'Sep 2017',
                endDate: 'Dec 2020',
                company: 'Amazon / AWS',
                position: 'Software Development Manager III',
                keywords: [
                    'Payment Services',
                    'AWS',
                    'Route 53',
                    'Agile',
                    'People Management',
                    'Delivery Management',
                    'Risk Management',
                ],
                description: [
                    [
                        `Proposed and implemented an engineering-wide "Going off-call" policy, increasing inclusiveness and belonging`,
                        `Became a certified Cultural Competences for Teams instructor, increasing inclusiveness and diversity awareness to the many hundreds of employees that took the training.`,
                        `Part of the Software Development Manager Peer Advisory board, helping new managers onboard and be successful in the company`,
                        `Promoted to Software Development Manager III`,
                    ],
                    `Amazon Payments`,
                    [
                        `Team owning 2 charters (International Expansion integrations and Payment on Delivery)`,
                        `Delivered amazon.com.tr (Amazon Turkey) payments integration. This multi-year project involved weekly collaboration and coordination with different teams, roles, partners, vendors in different countries.`,
                        `First team to start PSD2 work that enabled Amazon to stay complaint in Europe (SEPA DD)`,
                    ],
                    `AWS Route53`,
                    [
                        `Started a team from scratch, hiring 7 engineers`,
                        `Responsible for maintaining existing and building new generations of different Route53's User Experience (Consoles) with measurable operational, accessibility and usability improvements.`,
                        `Owned 5 different products in 2 different tech stacks, serving different sub- orgs with different stakeholders.`,
                        `Launched two world-wide projects and expanded our presence to multiple new partitions and regions.`,
                        `Improved Route53 org's sourcing efficiency by ~32% and our candidate diversity by ~11%.`,
                    ],
                ],
            },
            {
                startDate: 'Apr 2016',
                endDate: 'Feb 2017',
                company: 'Brandwatch',
                position: 'Team Lead & Senior Developer',
                keywords: [
                    'Node',
                    'Javascript',
                    'Require',
                    'Backbone',
                    'Underscore',
                    'HTML 5',
                    'CSS 3',
                    'Highcharts',
                    'jQuery',
                    'Mustache',
                    'BDD',
                    'Jasmine',
                    'Phantom',
                    'REST',
                    'Scrum',
                    'GitHub',
                    'JIRA',
                ],
                description: [
                    `Moved back to Germany and Brandwatch. After 8 months, I have become the team lead.`,
                    [
                        `Worked on existing and new features on their main product (Analytics)`,
                        `Wrote a script to perform a massive refactor (thousands of files) to update a ~5 year old jQuery codebase (with several breaking changes) to the latest version, improving bundle size, patching security vulnerabilities, improving performance on some DOM operations and enabling new jQuery features for the team to use`,
                        `Tracking overall progress of the team and removing blockers`,
                        `Helping the PM with Scrum ceremonies and prioritization`,
                        `Having local, more frequent 1-1s with the team`,
                    ],
                ],
            },
            {
                startDate: 'Apr 2015',
                endDate: 'Apr 2015',
                company: 'X-Team (Remote)',
                position: 'Full stack developer',
                keywords: ['Node', 'Javascript', 'React', 'Flux', 'LevelDB', 'Tape', 'Highcharts', 'jQuery', 'BPM'],
                description: [
                    'Hired by the awesome remote company X-Team to help researching, planning and developing the next phase of X-Labs (their open source initiative) and other internal projects involving IndexedDB. Great team, expert people, cool tech and tools.',
                ],
            },
            {
                startDate: 'Jun 2014',
                endDate: 'Mar 2016',
                company: 'DataEasy',
                position: 'Software Development Manager',
                keywords: [
                    'Scrum',
                    'XP',
                    'Kanban',
                    'SemVer',
                    'BPM',
                    'Software Testing',
                    'Freetest',
                    'Testlink',
                    'DevOps',
                    'Jenkins',
                    'Continuous Integration',
                    'Shell Scripting',
                    'Java EE',
                    'Maven',
                    'GitHub',
                    'New Relic',
                    'Node',
                    'Docker',
                    'Management',
                ],
                description: [
                    `DataEasy provides different solutions for end-to-end electronic document process management and automation. It has Brazil's biggest private and government organizations as their clients.`,
                    `Technical contributions:`,
                    [
                        `Managed 5 teams and 4 charters (all their products)`,
                        `Hired for a new team from scratch (5 engineers and 1 Business Analyst)`,
                        `Migrated the company's infrastructure to Git and Github`,
                        `Implement Semantic Versioning to all products in the company`,
                        `Implemented the company's first automated release script`,
                        `Create their first CI pipeline with Jenkins and Github`,
                        `Introduced Slack to the company and create a set of ChatOps commands to manage releases`,
                        `The points above enabled me to introduce the concept of "DevOps" in the company, enabling engineers to prep releases on their own with confidence and efficiency, enabling IT department (previously preparing the releases) to stay small and lean`,
                        `Introduced advanced monitoring in our applications (New Relic)`,
                    ],
                    `Organizational contributions:`,
                    [
                        `Created "Funky Fridays": bi-weekly innovation/learning days where employees could experiment with new technologies and solutions, prepare a tech talk for the company, etc`,
                        `Documented all process in the engineering department in BPMN and presented to all employees. That tacit knowledge was now documented and allowed us to identify rooms for improvement, enabling employees to also think about improvements and to better understand the organization in general, facilitating career growth and hence retention`,
                        `Collaborated with local University and had a few senior engineers join me in automated tests course provided by top professors. This combined with the above allowed us to streamline our testing cycles, reducing a big bottleneck in our release cycle`,
                        `Helped choose a new ticketing system for the company`,
                    ],
                ],
            },
            {
                startDate: 'Nov 2013',
                endDate: 'Jan 2016',
                company: 'GOJS User Group',
                position: 'Cofounder / Volunteer',
                keywords: ['Node', 'Javascript'],
                description: [
                    `Founded and ran the first Javascript user group of the state.`,
                    [
                        `Workshops planning and organizing`,
                        `Presenting talks`,
                        `Community moderation`,
                        `Website creation and maintenance,`,
                    ],
                ],
            },
            {
                startDate: 'May 2014',
                endDate: 'Jan 2017',
                company: 'SENAC Goiás',
                position: 'Consultant',
                keywords: ['Node', 'Javascript'],
                description: [
                    `SENAC is the largest agency for professional education in Brazil, present in more than 1800 cities. This was a short job as a consultant on new web technologies and architectures to aid their team and organization towards a more robust and modern system architecture, developer happiness and productivity.`,
                ],
            },
            {
                startDate: 'Apr 2013',
                endDate: 'Nov 2013',
                company: 'Brandwatch',
                position: 'Senior Developer',
                keywords: [
                    'Node',
                    'Javascript',
                    'Require',
                    'Backbone',
                    'Underscore',
                    'HTML 5',
                    'CSS 3',
                    'Highcharts',
                    'jQuery',
                    'Mustache',
                    'BDD',
                    'Jasmine',
                    'Phantom',
                    'REST',
                    'Scrum',
                    'GitHub',
                    'JIRA',
                ],
                description: [
                    `Worked on existing and new features on their main product (Analytics). Wrote a simple codemod to organize and format files, reducing future diff sizes and improving readability of the entire codebase.`,
                ],
            },
            {
                startDate: 'Apr 2012',
                endDate: 'Mar 2013',
                company: 'Content Fleet',
                position: 'Team Lead & Senior Developer',
                keywords: [
                    'Node',
                    'MongoDB',
                    'Javascript',
                    'Require',
                    'Backbone',
                    'Underscore',
                    'HTML 5',
                    'CSS 3',
                    'Highcharts',
                    'jQuery',
                    'REST',
                    'Scrum',
                    'SVN',
                    'Shell Script',
                    'Pivotal Tracker',
                ],
                description: [
                    `Worked as frontend-focused full stack engineer.`,
                    [
                        `Developed RESTful APIs, and their main MVC application.`,
                        `Created the company's first automated deploy script.`,
                        `Sped up the app's performance by minimizing the amount of network calls, introducing tools to minimize source code, removing dead code, downsampling raster images, etc.`,
                        `Improved the app's UX and performance in high resolution displays by drawing icons in pure CSS, converting images to vectors (SVG), etc.`,
                    ],
                    `Became the Frontend Team Lead. Additional responsibilities:`,
                    [
                        `Responsible for the team's conventions, refactorings, architectural decisions and app performance improvements.`,
                        `Responsible for training team members and new hires.`,
                    ],
                ],
            },
            {
                startDate: 'Fev 2007',
                endDate: 'Mar 2012',
                company: 'Goiás State Government',
                position: 'Full Stack Developer',
                keywords: ['Java EE', 'Velocity', 'SQL', 'HTML', 'Javascript', 'jQuery', 'CSS 3', 'SVN', 'UX'],
                description: [
                    [
                        `Worked as full stack engineer on "HR Net": the State's human resources web application responsible for payments, vacations, contracts, leaves, etc`,
                        `Proposed and added several performance, usability and accessibility improvements, impacting hundreds of thousands of daily users`,
                        `Became a Certified Java Programmer`,
                    ],
                ],
            },
            {
                startDate: '2004',
                endDate: '2005',
                company: 'DR Sistemas & Interagi',
                position: 'Trainee Developer',
                keywords: ['Java EE', 'Struts', 'Hibernate', 'SQL', 'JSP', 'PHP', 'MySQL', 'HTML', 'CSS', 'SVN', 'CVS'],
                description: [
                    'Interagi and DR were where I had my internships - 6 months each.',
                    [
                        'At Interagi, I developed CRUD applications in PHP, MySQL and HTML and some image processing via PHP',
                        'At DR Sistemas, I developed an application for the public law sector. Responsible for collecting specs from Business and implementing them in Java',
                    ],
                ],
            },
            {
                startDate: 'Jan 2003',
                endDate: 'Dec 2014',
                company: 'Freelancer',
                position: 'Software Developer & Consultant',
                keywords: [
                    '12 Factor Apps',
                    'Web Development',
                    'Team Coaching',
                    'Individual Coaching',
                    'Agile Methodologies',
                    'Web Languages',
                    'Web Services',
                    'REST',
                    'Software Testing',
                    'Software Quality',
                    'Continuous Integration',
                ],
                description: [
                    'Some companies I have consulted for:',
                    'Vega Sistemas, Goiânia, Brazil — Consultancy on migrating a desktop application to web platform. Tech, tools and paradigms shift.',
                    'SENAC Goiás, Goiânia, Brazil — Consultancy on web development, best practices, productivity tools, agile methodologies and comparison of dynamic versus compiled languages.',
                    'Federal University of Goiás — Development of the Public contest (Vestibular) system and website.',
                ],
            },
        ],
        instructorOrSpeaker: [
            {
                date: '26 Oct 2018',
                location: 'Berlin, Germany',
                venue: 'Amazon',
                title: 'Debugging Complex Things',
            },
            {
                date: '03 Mar 2017',
                location: 'Berlin, Germany',
                venue: 'EuroStaff Group',
                title: 'Debugging Complex Things',
            },
            {
                date: '08 Nov 2016',
                location: 'Berlin, Germany',
                venue: 'Brandwatch',
                title: 'Debugging Complex Things',
            },
            {
                date: '18 Feb 2016',
                location: 'Goiânia, Brazil',
                venue: 'DataEasy Ltda',
                title: '"Areas of Responsibility Model"',
            },
            {
                date: '05 Feb 2016',
                location: 'Goiânia, Brazil',
                venue: 'DataEasy Ltda',
                title: '"SMART Goals"',
            },
            {
                date: '20 Nov 2015',
                location: 'Goiânia, Brazil',
                venue: 'DataEasy Ltda',
                title: '"12 Factor Apps"',
            },
            {
                date: '30 Oct 2015',
                location: 'Goiânia, Brazil',
                venue: 'DataEasy Ltda',
                title: '"Developing Peopleware"',
            },
            {
                date: '17 Oct 2015',
                location: 'Goiânia, Brazil',
                venue: 'IV JoinCommunity',
                title: '"Developing Peopleware"',
            },
            {
                date: '17 Oct 2015',
                location: 'Goiânia, Brazil',
                venue: 'IV JoinCommunity',
                title: '"IoT: Introducing Tessel"',
            },
            {
                date: '16 Sep 2015',
                location: 'Goiânia, Brazil',
                venue: 'GOJS 7min.js',
                title: '"Meteor.js"',
            },
            {
                date: '01 Sep 2015',
                location: 'Goiânia, Brazil',
                venue: 'Federal University of Goiás',
                title: '"Developing a career"',
            },
            {
                date: '14 Ago 2015',
                location: 'Goiânia, Brazil',
                venue: 'Pontifical Catholic University of Goiás',
                title: '"Developing Peopleware"',
            },
            {
                date: '08 Jun 2015',
                location: 'Goiânia, Brazil',
                venue: 'Federal University of Goiás',
                title: '"Programming Languages"',
            },
            {
                date: '20 Mar 2015',
                location: 'Goiânia, Brazil',
                venue: 'Federal University of Goiás',
                title: '"Software Engineering at DataEasy"',
            },
            {
                date: '31 May 2014',
                location: 'Goiânia, Brazil',
                venue: 'III Join Community',
                title: '"Modern JS: from Coder to Shareholder"',
            },
            {
                date: '29 Mar 2014',
                location: 'Goiânia, Brazil',
                venue: 'I Workshop GOJS',
                title: '"Javascript Promises"',
            },
            {
                date: 'Jul 2014',
                location: 'Goiânia, Brazil',
                venue: 'DataEasy Brown Bag Sessions',
                title: ['"Introduction to Agile Methodologies"', '"Git & GitHub basics"'],
            },
            {
                date: '14 Nov 2013',
                location: 'Goiânia, Brazil',
                venue: 'Absolut Software - 12minutes.me',
                title: '"Cultural Intelligence and the Connection Economy"',
            },
            {
                date: '17 and 18 Feb 2011',
                location: 'Goiânia, Brazil',
                venue: 'SEBRAE',
                title: '"How tango can make you a better (business) man"',
            },
            {
                date: '09 Apr 2011',
                location: 'Itapuranga, Brazil',
                venue: 'I LatAm Free Software Installation Festival (FLISOL)',
                title: '"Entrepreneurship with free software"',
            },
            {
                date: 'Ago 2011',
                location: 'Goiânia, Brazil',
                venue: 'Computer, Electrical and Civil Engineering graduation',
                title: 'Graduation Ceremony Speech',
            },
            {
                date: 'Ago 2009',
                location: 'Goiânia, Brazil',
                venue: 'VI Goiás Forum of Free Software (FGSL)',
                title: '"Introduction to Ruby Language"',
            },
            {
                date: 'June 2009',
                location: 'Goiânia, Brazil',
                venue: 'Goiás State Government',
                title: 'LibreOffice instructor',
            },
        ],
        volunteer: [
            {
                date: '2014; 2015',
                location: 'Goiânia, Brazil',
                organization: 'Join Community',
                position: 'Co-organizer & speaker',
                keywords: ['Javascript', 'Node', 'Talks', 'Community events', 'Leadership', 'Career'],
            },
            {
                date: '2012; 2014',
                location: 'Goiânia, Brazil',
                organization: `Napoleon Hill Institute's Master Mind`,
                position: 'Lead auxiliary instructor',
                keywords: ['Leadership', 'Public Speaking', 'Coaching', 'Effective Communication', 'Time managing'],
            },
            {
                date: '2008 – 2011',
                location: 'Goiânia, Brazil',
                organization: 'Grupo Arte Nascente (GAN)',
                position: 'Actor & Web Developer',
                keywords: ['PHP', 'NGO', 'Art', 'Theater', 'Communication', 'Non-for profit'],
            },
            {
                date: '2006 – 2015',
                location: 'Goiânia, Brazil',
                organization: 'Zapt Arteatral',
                position: 'Actor, Web Developer, President, Artistic Director & Communication Coordinator',
                keywords: ['PHP', 'Art', 'Theater', 'Communication', 'Non-for profit'],
            },
            {
                date: '2007 – 2009',
                location: 'Goiânia, Brazil',
                organization: 'AIESEC Brazil / GO',
                position: 'Marketing, Communication & Information Management teams',
                keywords: ['Marketing', 'Public Relations', 'External Communication', 'Internal Communication'],
            },
            {
                date: '2000 – 2008',
                location: 'Goiânia, Brazil',
                organization: 'Mocidade Espírita André Luiz',
                position: 'Coordinator, Speaker & Member',
                keywords: ['Spiritualism', 'Leadership', 'Events'],
            },
        ],
    },
    education: {
        academyCourses: [
            {
                title: 'Business Process Management, MBA',
                date: 'Dec 2017',
                school: 'IT Management Institute (IGTI)',
                location: 'Brazil',
                info: [],
            },
            {
                title: 'Computer Engineering, Bachelor',
                date: 'Jun 2011',
                school: 'Federal University of Goiás',
                location: 'Brazil',
                info: ['Extra studies on Software Engineering', 'Relative average grade: 85%'],
            },
            {
                title: 'Computer Science, Visiting Student',
                date: '2010/1',
                school: `Saint Mary's University`,
                location: 'Canada',
                info: ['2nd round on Trumped Competition', 'Emerging Leaders of America Scholarship'],
            },
        ],
        relevantCourses: [
            {
                title: 'Foundations of Cybersecurity',
                school: 'Google',
                date: 'Feb 2024',
                duration: 80,
            },
            {
                title: 'Generative AI for Leaders',
                school: 'Vanderbilt University',
                date: 'Jan 2024',
                duration: 15,
            },
            {
                title: 'Prompt Engineering Specialization',
                school: 'Vanderbilt University',
                date: 'Dec 2023',
                duration: 80,
            },
            {
                title: 'Machine Learning Specialization',
                school: 'Stanford University',
                date: 'Nov 2023',
                duration: 80,
            },
            {
                title: 'Inclusive Leadership: The Power of Workplace Diversity',
                school: 'University of Colorado',
                date: 'Oct 2021',
                duration: 60,
            },
            {
                title: 'Developing on AWS',
                school: 'AWS Training Center',
                date: 'May 2020',
                duration: 32,
            },
            {
                title: 'Architecting on AWS',
                school: 'AWS Training Center',
                date: 'April 2020',
                duration: 32,
            },
            {
                title: 'DevSecOps on AWS',
                school: 'AWS Training Center',
                date: 'Feb 2020',
                duration: 32,
            },
            {
                title: `Search Inside Yourself Leadership Program`,
                school: `SYILI, LEAD & Google`,
                date: 'Sep 2016',
                duration: 15,
            },
            {
                title: 'React.js with Flux',
                school: 'FrontendMasters',
                date: 'Jun 2016',
                duration: 4.5,
            },
            {
                title: 'Kick Off Koa.js',
                school: 'NodeSchool',
                date: 'Oct 2015',
                duration: 4,
            },
            {
                title: 'Learn Sass',
                school: 'NodeSchool',
                date: 'Sep 2015',
                duration: 2,
            },
            {
                title: 'Learn Generators',
                school: 'NodeSchool',
                date: 'Sep 2015',
                duration: 1,
            },
            {
                title: 'WebRTC Fundamentals',
                school: 'PluralSight',
                date: 'Aug 2015',
                duration: 1.66,
            },
            {
                title: 'Level DB',
                school: 'NodeSchool',
                date: 'Apr 2015',
                duration: 4,
            },
            {
                title: 'Business Process Management (BPM)',
                school: 'BP Company; 16h',
                date: '2014',
                duration: 16,
            },
            {
                title: 'Freetest (TMMi based)',
                school: 'Federal University of Goiás',
                date: '2014',
                duration: 100,
            },
            {
                title: 'Startup Engineering',
                school: 'Stanford / Coursera',
                date: '2013',
                duration: 70,
            },
            {
                title: 'Projects on Carbon Credits',
                school: 'Eficiência Institute',
                date: '2012',
                duration: 20,
            },
            {
                title: 'Leadership, Interpersonal Intelligence and Effective Communication',
                school: `Napoleon Hill Institute's Master Mind`,
                date: '2011',
                duration: 48,
            },
            {
                title: 'Empretec Seminar',
                school: 'SEBRAE',
                date: '2011',
                duration: 60,
            },
            {
                title: 'Immersion Behavior Driven Development',
                school: 'e-Genial',
                date: '2010',
                duration: 12,
            },
            {
                title: 'Immersion Ruby on Rails',
                school: 'e-Genial',
                date: '2010',
                duration: 12,
            },
            {
                title: 'Java Web',
                school: 'SENAI FATESG',
                date: '2007',
                duration: 95,
            },
            {
                title: 'Software Development Process',
                school: 'Government School',
                date: '2007',
                duration: 40,
            },
            {
                title: 'Linux (basic, intermediate, advanced)',
                school: '3Way Networks',
                date: '2006',
                duration: 40,
            },
            {
                title: 'Web accessibility; XSLT; Tableless',
                school: 'Atípico',
                date: '2005',
                duration: 20,
            },
            {
                title: 'Information Systems workshop',
                school: 'UFG',
                date: '2004',
                duration: 32,
            },
            {
                title: 'Advanced Adobe Flash and Actionscript',
                school: 'SENAC',
                date: '2004',
                duration: 56,
            },
            {
                title: 'Graphic Projects workshop',
                school: 'SENAC',
                date: '2003',
                duration: 4,
            },
            {
                title: 'Web Design',
                school: 'SENAC',
                date: '2002',
                duration: 120,
            },
            {
                title: 'Programming logic',
                school: 'SENAC',
                date: '2001-2002',
                duration: 90,
            },
        ],
        relevantEvents: [
            {
                title: 'WebDevCon',
                location: 'Seattle, USA',
                date: '16-19 Apr 2019',
            },
            {
                title: 'AWS Console Unconf',
                location: 'Seattle, USA',
                date: '29-30 Jan 2019',
            },
            {
                title: 'Web Summit',
                location: 'Lisbon, Portugal',
                date: '7-10 Nov 2016',
            },
            {
                title: 'CodeMotion Conf',
                location: 'Berlin, Germany',
                date: '24-25 Oct 2016',
            },
            {
                title: 'TEDx Goiânia',
                location: 'Goiânia, Brazil',
                date: '21 Oct 2015',
            },
            {
                title: '4th Join Community',
                location: 'Goiânia, Brazil',
                date: '16-17 Oct 2015',
            },
            {
                title: 'AndYet Conf',
                location: 'Richland, USA',
                date: '06-08 Oct 2015',
            },
            {
                title: 'Google Developers Group DevFest 2014',
                location: 'Goiânia, Brazil',
                date: '17 Sep 2014',
            },
            {
                title: '3rd Join Community',
                location: 'Goiânia, Brazil',
                date: '30-31 Mai 2014',
            },
            {
                title: 'Analyzing network vulnerabilities',
                location: 'Goiânia, Brazil',
                date: '26 Apr 2014',
            },
            {
                title: '19th Convendas (Sales congress)',
                location: 'Goiânia, Brazil',
                date: '15 Mar 2014',
            },
            {
                title: 'JSConf.eu',
                location: 'Berlin, Germany',
                date: '14-15 Sep 2013',
            },
            {
                title: 'Reject.js',
                location: 'Berlin, Germany',
                date: '12 Sep 2013',
            },
            {
                title: 'Ruby Conf Brazil',
                location: 'São Paulo, Brazil',
                date: '3-4 Nov 2011',
            },
            {
                title: 'International Conf of Innovative Cities',
                location: 'Curitiba, Brazil',
                date: '17-20 Mai 2011',
            },
            {
                title: 'I LatAm Free Software Installation Festival',
                location: 'Itapuranga, Brazil',
                date: '9 Apr 2011',
            },
            {
                title: 'X Software Engineering Journey of Goiás',
                location: 'Goiânia, Brazil',
                date: '24, 25 Sep 2010',
            },
            {
                title: 'VIII Software Engineering Journey of Goiás',
                location: 'Goiânia, Brazil',
                date: '3,4 Oct 2008',
            },
            {
                title: 'I IT Governance Seminar',
                location: 'Goiânia, Brazil',
                date: '31 Mar 2008',
            },
            {
                title: 'Java: JEDI Initiative',
                location: 'Goiânia, Brazil',
                date: 'Sep 2007',
            },
            {
                title: 'II Goiás Forum of Free Software',
                location: 'Goiânia, Brazil',
                date: '1 Oct 2005',
            },
            {
                title: 'IBM: Migrating and developing for Linux',
                location: 'Goiânia, Brazil',
                date: '18 May 2005',
            },
            {
                title: 'I LatAm Free Software Installation Festival',
                location: 'Goiânia, Brazil',
                date: '2 Apr 2005',
            },
            {
                title: 'I Electric and Computer Engineering Week',
                location: 'Goiânia, Brazil',
                date: '8-12 Nov 2004',
            },
            {
                title: 'II Java Gyn',
                location: 'Goiânia, Brazil',
                date: '15 July 2004',
            },
            {
                title: 'IX Web Design Meeting',
                location: 'Brasília, Brazil',
                date: '15 Jul 2004',
            },
            {
                title: 'I National IT Congress',
                location: 'Goiânia, Brazil',
                date: 'May 2004',
            },
        ],
    },
    languages: [
        { name: 'Portuguese', level: 'Native' },
        { name: 'English', level: 'Fluent' },
        { name: 'German & Spanish', level: 'Basic' },
    ],
    noteworthy: [
        'AWS Certified Cloud Practitioner; Nov 2018',
        '"MasterMind Commender and Class\' Name" title on MasterMind training in Leadership, Interpersonal Intelligence and Effective Communication; 2011',
        '"Best presentation" prize on MasterMind training in Leadership, Interpersonal Intelligence and Effective Communication; 2011',
        '"Self Overcoming" prize on Empretec Entrepreneurship Seminar; 2011',
        'IELTS (International English Language Testing System), 8 points in 2017 (89%)',
        'KITE (Kaplan International Tools for English), C2 Level - Proficient (564 points) in 2015',
        'TOEFL (Test of English as a Foreign Language), 108 points in 2011 (90%); 103 points in 2009 (86%)',
        'Sun Certified Java Programmer (SCJP) for the Java 5 Platform; 2008',
    ],
    offTopic: {
        books: {
            software: [
                { title: 'Shape Up: ', subtitle: 'Stop Running in Circles and Ship Work that Matters', author: 'Ryan Singer' },
                { title: 'Mastering Vim', author: 'Jovica Ilic' },
                { title: 'The End of Privacy', author: 'B.J. Mendelson' },
                {
                    title: 'The Tao of Tmux and Terminal Tricks',
                    author: 'Tony Narlock',
                },
                {
                    title: 'InnerSource: ',
                    subtitle: 'Keys to collaboration and productivity inside your company',
                    author: 'Andy Oram',
                },
                {
                    title: 'Webpack from apprentice to master',
                    author: 'Juno Vepsäläinen',
                },
                { title: 'Clean Code', author: 'Robert C. Martin' },
                {
                    title: 'Getting Started with Meteor.js',
                    author: 'Isaac Strack',
                },
                { title: 'Practical VIM', author: 'Drew Neil' },
                { title: 'Pro Git', author: 'Scott Chacon' },
                {
                    title: 'Developing Backbone Applications',
                    author: 'Addy Osmani',
                },
                {
                    title: 'Javascript - The Good Parts',
                    author: 'Douglas Crockford',
                },
                { title: 'Code Simplicity', author: 'Max Kanata-Alexander' },
                { title: 'The Node Beginner Book', author: 'Manuel Kiessling' },
                { title: 'Learn Rails 3 by example', author: 'Michael Hartl' },
                {
                    title: 'Agile web development with Rails 2',
                    author: 'Dave Thomas, David Heinemeier Hanson',
                },
                {
                    title: 'Rework',
                    author: 'Jason Fried, David Heinemeier Hanson',
                },
                {
                    title: 'Rails for Java Developers',
                    author: 'Stuart Halloway, Justin Gehtlan',
                },
                { title: 'Getting Real', author: '37 Signals' },
                {
                    title: 'Head First: Servlets & JSP',
                    author: 'Kathy Sierra, Bryan Basham, Bert Bates',
                },
                {
                    title: 'Head First: Design Patterns',
                    author: 'E. Freeman, E. Robson, B. Bates, K. Sierra',
                },
                {
                    title: 'Regular Expressions',
                    author: 'Aurélio Marinho Vargas',
                },
                { title: 'Java: How to Program', author: 'Deitel' },
            ],
            softSkills: [
                {
                    title: 'Team Topologies: ',
                    subtitle: 'Organizing Business and Technology Teams for Fast Flow',
                    author: 'Matthew Skelton, Manuel Pais',
                },
                {
                    title: 'Atomic Habits: ',
                    subtitle: 'An Easy & Proven Way to Build Good Habits & Break Bad Ones',
                    author: 'James Clear',
                },
                {
                    title: 'Find Your Why: ',
                    subtitle: 'A Practical Guide to Discovering Purpose for You and Your Team',
                    author: 'Simon Sinek, David Mead & Peter Docker',
                },
                { title: 'The Infinite Game', author: 'Simon Sinek' },
                {
                    title: `Man's Search for Meaning`,
                    author: 'Viktor E. Frankl',
                },
                { title: 'Thinking, Fast and Slow', author: 'Daniel Kahneman' },
                {
                    title: 'The Subtle Art of Not Giving a F*ck: ',
                    subtitle: 'A Counterintuitive Approach to Living a Good Life',
                    author: 'Mark Manson',
                },
                {
                    title: "It Doesn't have to be Crazy at Work",
                    author: 'Jason Fried, David Heinemeier Hansson',
                },
                {
                    title: 'The First 90 Days: ',
                    subtitle: 'Critical Success Strategies for New Leaders at All Levels',
                    author: 'Michael D. Watkins',
                },
                {
                    title: 'Dare to Lead: ',
                    subtitle: 'Brave work. Tough conversations. Whole hearts.',
                    author: 'Brené Brown',
                },
                {
                    title: 'The Coaching Habit: ',
                    subtitle: 'Say Less, Ask More & Change the Way Your Lead Forever',
                    author: 'Michael Bungay Stanier',
                },
                {
                    title: 'The First 90 Days: ',
                    subtitle: 'Critical Success Strategies for New Leaders at All Levels',
                    author: 'Michael D. Watkins',
                },
                {
                    title: 'Collective Intelligence: ',
                    subtitle: `Mankind's Emerging World in Cyberspace`,
                    author: 'Pierre Lévy',
                },
                {
                    title: 'The Checklist Manifesto: ',
                    subtitle: 'How to get things right',
                    author: 'Atul Gawande',
                },
                {
                    title: 'Start With Why: ',
                    subtitle: 'How great leaders inspire everyone to take action',
                    author: 'Simon Sinek',
                },
                {
                    title: 'Moral Tribes: ',
                    subtitle: 'Emotion, reason and the gap between us and them',
                    author: 'Joshua Greene',
                },
                {
                    title: 'Drive: ',
                    subtitle: 'The surprising truth about what motivates us',
                    author: 'Daniel H. Pink',
                },
                { title: 'The Power of Habit', author: 'Charles Duhigg' },
                {
                    title: 'Difficult Conversations',
                    author: 'Douglas Stone, Sheila Heen, Bruce Patton',
                },
                {
                    title: 'Leading Snowflakes: ',
                    subtitle: 'The Engineering Manager Handbook',
                    author: 'Oren Ellenbogen',
                },
                { title: 'Managing Oneself', author: 'Peter Drucker' },
                { title: 'The soul of leadership', author: 'Deepak Chopra' },
                { title: 'Managing Humans', author: 'Michael Lopp' },
                { title: 'The Purpose Economy', author: 'Aaron Hurst' },
                {
                    title: '7 Spiritual Laws of Success',
                    author: 'Deepak Chopra',
                },
                {
                    title: 'Leading with Cultural Intelligence',
                    author: 'David Livermore, PhD',
                },
                { title: `Times' Triad`, author: 'Christian Barbosa' },
                {
                    title: 'The Power of Vulnerability',
                    author: 'Brené Brown, PhD',
                },
                { title: `A Leader's Diary`, author: 'Luciano Pires' },
                { title: 'Disguised Opportunities', author: 'Carlos Domingos' },
                {
                    title: 'Leader with a Master Mind',
                    author: 'Jamil Albuquerque',
                },
                {
                    title: 'The Icarus Deception: ',
                    subtitle: 'How High Will You Fly',
                    author: 'Seth Godin',
                },
                {
                    title: 'Tribes: ',
                    subtitle: 'We need you to guide us',
                    author: 'Seth Godin',
                },
                { title: 'Startup', author: 'Jessica Livingston' },
                { title: 'Do The Work', author: 'Steven Pressfield' },
                { title: 'The Dip', author: 'Seth Godin' },
                {
                    title: 'V is for Vulnerable: ',
                    subtitle: 'Life outside the comfort zone',
                    author: 'Seth Godin',
                },
                { title: 'Anything You Want', author: 'Derek Sivers' },
                {
                    title: 'What is Your Legacy? ',
                    subtitle: 'Provocative Thoughts About Ethics, Leadership and Management',
                    author: 'Mario Sergio Cortella',
                },
                {
                    title: `The Entrepreneur's Guide to Customer Development`,
                    author: 'Brant Cooper',
                },
                {
                    title: 'The Monk and the Executive',
                    author: 'James C. Hunter',
                },
                {
                    title: `The Triumph's Law for the 21st century`,
                    author: 'Napoleon Hill, Jamil Albuquerque',
                },
                {
                    title: 'The Art of Dealing With People',
                    author: 'Jamil Albuquerque',
                },
                { title: 'How to Grow a Business', author: 'Eric Crowell' },
                { title: 'Getting Things Done', author: 'David Allen' },
            ],
        },
        freeTime: [`I'm launching a nonprofit & open source initiative with a friend: https://konsilos.com`],
    },
};

function getKeywords(obj: any): string[] {
    let keywords: string[] = [];
    for (let key in obj) {
        if (key === 'keywords') {
            keywords = keywords.concat(obj[key] as string[]);
        } else if (typeof obj[key] === 'object') {
            keywords = keywords.concat(getKeywords(obj[key] as object));
        }
    }
    return keywords;
}

const aiKeywords: string[] = [
    'Agile Methodologies',
    'Business Process Management',
    'Candidate Sourcing',
    'Career Growth',
    'Coaching and Mentoring',
    'Continuous Integration',
    'Cross-Functional Collaboration',
    'CV',
    'Curriculum Vitae',
    'DE&I (Diversity, Equity & Inclusion)',
    'DevOps',
    'Documentation',
    'Leadership',
    'Monitoring',
    'Operational Efficiency',
    'Organizational Strategy',
    'Performance Metrics',
    'Policy Development',
    'Postmortem Process',
    'Process Improvement',
    'Product Development',
    'Product Launch',
    'Project Management',
    'Public Speaking',
    'Resume',
    'Revenue Growth',
    'Remote Collaboration',
    'Software Development',
    'Software Development Lifecycle',
    'Software Engineering',
    'Stakeholder Engagement',
    'Team Management',
    'User Experience (UX)',
    'Vendor Relationships',
];
const myKeywords = getKeywords(cvData);
export const cvKeywords: string[] = [...new Set([...aiKeywords, ...myKeywords].map(s => s.toLowerCase()))].sort();
